apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: user-management
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: postgres-pv
  storageClassName: managed-csi
  resources:
    requests:
      storage: 5Gi

