apiVersion: v1
kind: PersistentVolume
metadata:
 name: postgres-pv
 labels:
   type: azure-disk
spec:
 capacity:
   storage: 10Gi            # match or be <= the actual disk size
 accessModes:
   - ReadWriteOnce
 persistentVolumeReclaimPolicy: Retain
 storageClassName: managed-csi   # use same class on PVC for binding
 csi:
   driver: disk.csi.azure.com
   volumeHandle: "/subscriptions/5a775aa2-0a21-483c-9818-460896054c2e/resourceGroups/rg-jamil-user-management/providers/Microsoft.Compute/disks/postgres-jamil-pv-disk"
   fsType: ext4
